### ISSUE TITLE
RuntimeError: size mismatch

### ISSUE THREAD

**Issue by borgiaE** [nizhib/pytorch-insightface#5]
When I run the example:
pytorch 1.5.0 un raspberry pi

Traceback (most recent call last):
  File "file.py", line 22, in <module>
    features = embedder(tensor.unsqueeze(0))[0]
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/insightface/iresnet.py", line 146, in forward
    x = self.fc(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py", line 1610, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [1 x 819200], m2: [25088 x 512] at /home/pi/pytorch/aten/src/TH/generic/THTensorMath.cpp:41

**Comment by nizhib** [comment]
The input image/tensor is expected to be 112x112, it was more likely 640x640 in your case.

By the way there is no magic in embedding random face-containing photos thus one must use some face detector and postprocessing (aligning) like in the original repo.
